fix: do not register providers inside of withConnection
sourcegraph/lsp-client pull request #42
Opened 2019-05-29 01:22 UTC by chrismwendt

Fixes https://github.com/sourcegraph/lsp-client/issues/41 by passing a flag `registerProviders` around internally.

This may or may not be a desirable solution, but at least it serves as something to discuss.

2019-05-29 16:40 UTC, lguychard approved these changes
I'm not extremely familiar with lsp-client, but at first glance I wouldn't have expected `withConnection()` to have side effects such as provider registration based on its prototype and docstring.

Based solely on that, this seems like a sensible fix.

2019-05-29 16:42 UTC, felixfbecker commented
Linking https://github.com/sourcegraph/lsp-client/issues/41#issuecomment-496825796

2020-01-29 15:13 UTC, efritz approved these changes

2020-01-29 15:22 UTC, felixfbecker requested changes
Just wanted to be explicit that I think this would not work because the connections are expected to be put in the cache (so they need providers too), see https://github.com/sourcegraph/lsp-client/issues/41#issuecomment-496825796. It's been a while since I looked at this though.

2020-01-29 15:30 UTC, efritz commented
Is it correct behavior on the sourcegraph side to invoke all providers when the provider set changes (even for providers that didn't de/re/un register)?

2020-01-31 19:25 UTC, chrismwendt commented
> Is it correct behavior on the sourcegraph side to invoke all providers when the provider set changes (even for providers that didn't de/re/un register)?

@efritz IMO it's incorrect. Linking "Do not call all providers when the set changes (it may be high time to take another stab at https://github.com/sourcegraph/sourcegraph/issues/2962#issuecomment-478389985)" https://github.com/sourcegraph/lsp-client/issues/41#issue-449554346

> I think this would not work because the connections are expected to be put in the cache (so they need providers too)

I'll take a stab at recording that bit in the connection map.

2020-01-31 21:50 UTC, chrismwendt commented
> > I think this would not work because the connections are expected to be put in the cache (so they need providers too)
> 
> I'll take a stab at recording that bit in the connection map.

I looked at this a bit closer and concluded that it's not a problem because the change in this PR never causes a root browsable in the Sourcegraph UI to be missing providers.

2020-01-31 21:53 UTC, merged